name: release
on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
    # QEMU
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    # Buildx
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v2
    # Docker login
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: octothorp.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    # Login, build & publish docker image
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        push: true
        tags: |
          octothorp.azurecr.io/hafnia:${{ steps.gitversion.outputs.NuGetVersionV2 }}
          octothorp.azurecr.io/hafnia:${{ steps.gitversion.outputs.Major }}${{ steps.gitversion.outputs.PreReleaseLabelWithDash }}
          octothorp.azurecr.io/hafnia:${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor }}${{ steps.gitversion.outputs.PreReleaseLabelWithDash }}
        build-args: RELEASE_VERSION=${{ steps.gitversion.outputs.NuGetVersionV2 }}
        platforms: linux/amd64, linux/arm64